[package]
name = "ntfs"
version = "0.1.0"
authors = ["Colin Finck <colin@reactos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.1", default-features = false }
binread = { version = "2.1.1", features = ["const_generics"], default-features = false }
byteorder = { version = "1.4.3", default-features = false }
bitflags = "1.2.1"
chrono = { version = "0.4.19", optional = true }
derive_more = "0.99.16"
displaydoc = { version = "0.2.1", default-features = false }
enumn = "0.1.3"
memoffset = "0.6.4"
strum_macros = "0.21.1"

[dev-dependencies]
anyhow = "1.0"

[features]
default = ["std"]
std = ["arrayvec/std", "binread/std", "byteorder/std"]

[[example]]
name = "ntfs-shell"
required-features = ["chrono"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
